CREATE TABLE BILL_SYNC_CACHE_SUCCESS 
(
TRANS_ID NUMBER(18), 
CUST_ID NUMBER(15), 
ORDER_ITEM_ID NUMBER(16), 
REQUEST CLOB, 
CREATE_DATE DATE, 
PART_ID NUMBER(9), 
PROCESS_DATE DATE
)
PARTITION BY LIST (PART_ID) 
(PARTITION P1  VALUES (1) , 
PARTITION P2  VALUES (2) , 
PARTITION P3  VALUES (3) , 
PARTITION P4  VALUES (4) , 
PARTITION P5  VALUES (5) , 
PARTITION P6  VALUES (6) , 
PARTITION P7  VALUES (7) , 
PARTITION P8  VALUES (8) , 
PARTITION P9  VALUES (9) , 
PARTITION P10  VALUES (10) , 
PARTITION P11  VALUES (11) , 
PARTITION P12  VALUES (12) ) ;

CREATE INDEX IDX_SYNC_SUCC_CUST ON BILL_SYNC_CACHE_SUCCESS (CUST_ID)    LOCAL;
CREATE INDEX IDX_SYNC_SUCC_ORDER_ITEM ON BILL_SYNC_CACHE_SUCCESS (ORDER_ITEM_ID)    LOCAL;
CREATE INDEX IDX_BILL_SYNC_CACHE_SUCCESS ON BILL_SYNC_CACHE_SUCCESS (TRANS_ID)    LOCAL;